name: hate_env
dependencies:
  - nomkl
  - python=3.7
  - pip
  - pip:
    - Flask==1.1.2
    - gunicorn==20.0.4
    - Jinja2==2.11.1
    - requests==2.23.0
    - urllib3==1.25.8
    - Werkzeug==1.0.0
    - newspaper3k==0.2.8
